package revision;

public class Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
int x =1;
int a[]= {1,2,3};

try {
a[10]=10/x;	
}
/*catch(ArrayIndexOutOfBoundsException e){
System.out.println("exception");
	}*/
finally {
	System.out.println("hiii");
	
}

System.out.println("end");

	}
}
